; AdventureTime per-character target quantities
Draught_of_Shimmering_Reflection_I=40
Draught_of_Shimmering_Reflection_II=5
Draught_of_Opulent_Healing_I=0
Draught_of_Opulent_Healing_II=0
Draught_of_Frenzied_Endurance_I=0
Draught_of_Frenzied_Endurance_II=0
Draught_of_Fleeting_Fortitude_I=50
Draught_of_Fleeting_Fortitude_II=0
Draught_of_Earthen_Grit_I=0
Draught_of_Earthen_Grit_II=0
Draught_of_Inferno_Ward_I=50
Draught_of_Inferno_Ward_II=0
Draught_of_the_Clear_Mind_I=50
Draught_of_the_Clear_Mind_II=0
Orb_of_Shadows=0
Emerald=0
Ruby=0
Diamond_Coin=0
